// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220311003916_20221003213200_CarMigration")]
    partial class _20221003213200_CarMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalPassgeiros")
                        .HasColumnType("INT(20)");

                    b.Property<int>("idLoc")
                        .HasColumnType("INT(20)");

                    b.Property<int>("TotLugares")
                        .HasColumnType("INT(20)");

                    b.Property<string>("AnoCarro")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(20)");
                    
                    b.Property<string>("Fotos")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
